spring.application.name=student-management-api

spring.datasource.url=jdbc:postgresql://localhost:5432/student_filter
spring.datasource.username=postgres
spring.datasource.password=Elsen4444

spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.hibernate.ddl-auto=update